server:
  port: 80
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./local
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
#  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/test?&serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    '[com.toy.live.mapper]': trace

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

upload:
  path: C:/upload/

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    